[package]
name = "rust_api_poc"
version = "0.1.0"
authors = ["Maximilien Andile <hello@maximilien-andile.com>"]

[[bin]]
name = "hello"

[dependencies]
iron = "0.5.0"
router = "0.5.0"
mysql = "12.0.3"